classdef SOC_LSTM_select_2 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %SOC_LSTM_select_2 Auto-generated custom layer
    % Auto-generated by MATLAB on 27-Mar-2026 17:38:12

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters

    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = SOC_LSTM_select_2(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [select_selectoutput] = predict(obj,select_lstmoutput)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [select_lstmoutput, select_lstmoutput_format] = soc_model.ops.permuteToReversePyTorch(select_lstmoutput, 'BTC', 3);
            [select_lstmoutput_numdims] = (int64(3));

            [select_selectoutput] = tracedPyTorchFunction(obj,select_lstmoutput,false,"predict");


            [select_selectoutput] = soc_model.ops.labelWithPropagatedFormats(select_selectoutput, 3, "BTC");
        end



        function [select_selectoutput] = forward(obj,select_lstmoutput)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [select_lstmoutput, select_lstmoutput_format] = soc_model.ops.permuteToReversePyTorch(select_lstmoutput, 'BTC', 3);
            [select_lstmoutput_numdims] = (int64(3));

            [select_selectoutput] = tracedPyTorchFunction(obj,select_lstmoutput,true,"forward");


            [select_selectoutput] = soc_model.ops.labelWithPropagatedFormats(select_selectoutput, 3, "BTC");
        end



        function [select_selectoutput] = tracedPyTorchFunction(obj,select_lstmoutput,isForward,predict)
            [select_selectoutput] = soc_model.ops.pySlice(select_lstmoutput,0,-1,-1,1,true,[3]);

        end

    end
end

